version: 2.1
jobs:
  compile:
   docker:
      - image: mrkhan007/aosp:latest 
   steps:
      - run1:
          name: get basic setup
          command: wget https://raw.githubusercontent.com/Ankits-lab/trail/main/setup.sh  
      - run2:
          name: build basic setup
          command: bash setup.sh
      - run3:
          name: get android setup
          command: wget https://raw.githubusercontent.com/Ankits-lab/trail/main/setup2.sh  
      - run4:
          name: build android setup
          command: bash setup2.sh
      - run5:
          name: get android sources 
          command: wget https://raw.githubusercontent.com/Ankits-lab/trail/main/lunch.sh  
      - run6:
          name: lunch android source
          command: bash lunch.sh
      - run7:
          name: mb
          no_output_timeout: 8h
          command: make bacon
      - run8:
          name: get copy upload script
          command: wget https://raw.githubusercontent.com/Ankits-lab/trail/main/lunch.sh  
      - run9:
          name: copy output to different location
          command: bash copy.sh
           
        
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
