version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:20.04
   steps:
      - run:
          name: OS setup 
          command: export DEBIAN_FRONTEND=noninteractive; export TZ=Asia/Kolkata; apt -qq update --fix-missing; apt -qq install -y git wget make
      - run:
          name: get basic setup
          command: wget https://raw.githubusercontent.com/Ankits-lab/trail/main/setup.sh
          no_output_timeout: 8h
      - run:
          name: build basic setup
          command: bash setup.sh
          no_output_timeout: 8h
      - run:
          name: get android setup
          command: wget https://raw.githubusercontent.com/Ankits-lab/trail/main/setup2.sh
          no_output_timeout: 8h
      - run:
          name: build android setup
          command: bash setup2.sh
          no_output_timeout: 8h
      - run:
          name: get device source
          no_output_timeout: 8h
          command: https://raw.githubusercontent.com/Ankits-lab/trail/main/device.sh
      - run:
          name: clone device source
          command: bash device.sh
          no_output_timeout: 8h
      - run:
          name: get lunch script 
          command: wget https://raw.githubusercontent.com/Ankits-lab/trail/main/lunch.sh
          no_output_timeout: 8h
      - run:
          name: lunch device 
          command: bash lunch.sh
          no_output_timeout: 8h
      - run:
          name: get copy upload script
          command: wget https://raw.githubusercontent.com/Ankits-lab/trail/main/copy.sh  
          no_output_timeout: 8h
      - run:
          name: copy output to different location
          command: bash copy.sh
          no_output_timeout: 8h       

workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
