version: 2.1
jobs:
  compile:
   docker:
      - image: mrkhan007/aosp:latest 
   steps:
      -run:
        name: get basic setup
        command: wget https://raw.githubusercontent.com/Ankits-lab/trail/main/setup.sh
        no_output_timeout: 3h
      -run:
        name: build basic setup
        command: bash setup.sh
        no_output_timeout: 3h
      -run:
        name: get android setup
        command: wget https://raw.githubusercontent.com/Ankits-lab/trail/main/setup2.sh
        no_output_timeout: 3h
      -run:
        name: build android setup
        command: bash setup2.sh
        no_output_timeout: 3h
      -run:
        name: get android sources 
        command: wget https://raw.githubusercontent.com/Ankits-lab/trail/main/lunch.sh
        no_output_timeout: 3h
      -run:
        name: lunch android source
        command: bash lunch.sh
        no_output_timeout: 3h
      -run:
        name: bacon
        command: make bacon
        no_output_timeout: 6h
      -run:
        name: get copy upload script
        command: wget https://raw.githubusercontent.com/Ankits-lab/trail/main/lunch.sh
        no_output_timeout: 3h
      -run:
        name: copy output to different location
        command: bash copy.sh
        no_output_timeout: 3h
           
        
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
